#3 - first working version

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -4,8 +4,19 @@
 # Called by "git commit" with no arguments.
 
 ## Generic settings
-matlabRoot="/c/Program Files/MATLAB/R2025a"
+matlabRoot="/c/Program Files/MATLAB/R2025b"
 matlabExe="$matlabRoot/bin/matlab"
+envdir=$USERPROFILE/Documents/MATLAB/cc4m/python/25.2
+
+# GIT repository root folder.
+gitRootFolder=$(git rev-parse --show-toplevel)
+
+#activate Python environment
+. $envdir/Scripts/activate
+
+echo "adapt PythonPath"
+export PYTHONPATH
+PYTHONPATH="$envdir/Lib;$PYTHONPATH"
 
 # Only rules with severity level equal to or higher than "severityLevelBoundary" will be included.
 severityLevelBoundary=10
@@ -16,16 +27,13 @@ configFile=MonkeyProofMATLABCodingStandard
 # List of extensions to include.
 supportedExtensions="\.m$|\.mlx$|\.slx$|\.mlapp$|\.mdl$"
 
-# GIT repository root folder.
-gitRootFolder=$(git rev-parse --show-toplevel)
-
 # Initialize variables.
 gitFullFiles=
 count=0
 
 ## The hook.
 # Loop over files to commit, just keep files to check.
-for file in $(git diff --cached --name-only --diff-filter=ACM); do
+for file in $(git diff  --name-only --diff-filter=ACM); do
   if echo "$file" | grep -qE "$supportedExtensions"; then
     echo "$file contains MATLAB code."
     if [ 1 -eq $count ]
@@ -42,24 +50,28 @@ done
 if test $count -eq 0 
 then
 	echo "No MATLAB files to check."
-	exit 0
+	#exit 0
 fi
 
 echo "Checking MATLAB files."
 
-matlabOutput=$("$matlabExe" -nodesktop -nodisplay -wait -sd "$gitRootFolder" -r "precommit_example('$gitFullFiles', '$configFile', $severityLevelBoundary)")
 
+matlabOutput=$(python precommit.py "$envdir/Lib" "$matlabExe" "$gitRootFolder" "precommit_example('$gitFullFiles', '$configFile', $severityLevelBoundary)")
 errorlevel=$?
+echo "return from python"
+echo "error: $errorlevel"
+echo "$matlabOutput"
+
+#matlabOutput=$("$matlabExe" -nodesktop -nodisplay -wait -sd "$gitRootFolder" -r "precommit_example('$gitFullFiles', '$configFile', $severityLevelBoundary)")
+
 
 if test $errorlevel -eq 0
 then
 	echo ok
-	echo "$matlabOutput"
-	exit 0
+	exit 1
 else
 	echo "Commit canceled! Critical guidelines are not followed in the M-files. This needs to be fixed first. A report opens that highlights the violations"
 	echo " "
-	echo "$matlabOutput"
 	exit 1		
 fi
 
